/**
 * Emit app/tokens.css from lib/tokens.ts (TRI-145, Phase A).
 *
 *   node scripts/tokens/emit-css.mjs          # writes app/tokens.css
 *   node scripts/tokens/emit-css.mjs --check  # exits 1 if the committed file is stale
 *
 * Node 24 strips TypeScript types natively, so the token file is imported as-is;
 * no build step, no dependency. The generated file is committed so the app
 * builds without running this, and the sync test keeps the two honest.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..");
// Windows needs a file:// URL for dynamic import of an absolute path.
const { TOKENS } = await import(pathToFileURL(resolve(root, "lib/tokens.ts")).href);

export function renderTokensCss(t = TOKENS) {
  const lines = [];
  const push = (s = "") => lines.push(s);

  push("/* GENERATED by scripts/tokens/emit-css.mjs from lib/tokens.ts — do not edit by hand. */");
  push("/* Run `npm run tokens` after changing lib/tokens.ts. */");
  push();

  const colourVars = (theme) => {
    const out = [];
    for (const [k, v] of Object.entries(t.color[theme])) out.push(`  --${k}: ${v};`);
    t.hz[theme].forEach((v, i) => out.push(`  --hz-${i + 1}: ${v};`));
    for (const [k, v] of Object.entries(t.section[theme])) out.push(`  --section-${k}: ${v};`);
    return out;
  };

  // `[data-theme="light"]` too, so a light block can sit inside a dark page
  // (the /dev/primitives gallery renders both themes side by side).
  push(':root, [data-theme="light"] {');
  for (const l of colourVars("light")) push(l);
  for (const [k, v] of Object.entries(t.cat)) push(`  --cat-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.layer)) push(`  --layer-${k.replace(/_/g, "-")}: ${v};`);
  push("}");
  push();
  push('[data-theme="dark"] {');
  for (const l of colourVars("dark")) push(l);
  push("}");
  push();

  push("/* Expose the tokens to Tailwind utilities (bg-canvas, text-label, rounded-card, bg-cat-a, …). */");
  push("@theme inline {");
  for (const k of Object.keys(t.color.light)) push(`  --color-${k}: var(--${k});`);
  for (const k of Object.keys(t.cat)) push(`  --color-cat-${k}: var(--cat-${k});`);
  t.hz.light.forEach((_, i) => push(`  --color-hz-${i + 1}: var(--hz-${i + 1});`));
  for (const k of Object.keys(t.layer)) push(`  --color-layer-${k.replace(/_/g, "-")}: var(--layer-${k.replace(/_/g, "-")});`);
  for (const k of Object.keys(t.section.light)) push(`  --color-section-${k}: var(--section-${k});`);
  push();
  for (const [k, v] of Object.entries(t.font)) push(`  --font-${k}: ${v};`);
  push();
  for (const [k, [size, lh]] of Object.entries(t.text)) {
    push(`  --text-${k}: ${size};`);
    push(`  --text-${k}--line-height: ${lh};`);
  }
  push();
  for (const [k, v] of Object.entries(t.radius)) push(`  --radius-${k}: ${v};`);
  for (const [k, v] of Object.entries(t.shadow)) push(`  --shadow-${k}: ${v};`);
  push("}");
  push();
  return lines.join("\n");
}

const target = resolve(root, "app/tokens.css");
const css = renderTokensCss();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8").replace(/\r\n/g, "\n");
  } catch {
    current = "";
  }
  if (current !== css) {
    console.error("app/tokens.css is stale — run `npm run tokens`.");
    process.exit(1);
  }
  console.log("tokens.css in sync");
} else {
  writeFileSync(target, css);
  console.log(`wrote ${target} (${css.length} bytes)`);
}
