import { type EmailOtpType } from "@supabase/supabase-js";
import { type NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Magic-link landing route. Handles both Supabase email flows:
 *  - token_hash + type — links generated by a customised email template
 *    ({{ .TokenHash }}), robust across devices/browsers.
 *  - code — the default template's ConfirmationURL → Supabase verify endpoint
 *    → PKCE redirect back here. Works when the link is opened in the same
 *    browser that requested it (the PKCE verifier lives in our cookies).
 * Either path sets the session cookie, then bounces to the app.
 */
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type") as EmailOtpType | null;
  const code = searchParams.get("code");
  const next = searchParams.get("next") ?? "/";

  const supabase = await createClient();

  if (token_hash && type) {
    const { error } = await supabase.auth.verifyOtp({ type, token_hash });
    if (!error) return NextResponse.redirect(new URL(next, request.url));
  } else if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code);
    if (!error) return NextResponse.redirect(new URL(next, request.url));
  }

  return NextResponse.redirect(new URL("/login?error=invalid-link", request.url));
}
